graph TD
    root(springmvcxsl)
    root --> meta[meta.yml]
    root --> notes[notes]
    notes --> run[run.txt]
    root --> pom[pom.xml]
    root --> src[src]
    src --> main[main]
    main --> java[java]
    java --> com[com]
    com --> example[example]
    example --> springmvcxsl_pkg[springmvcxsl]
    springmvcxsl_pkg --> controller[controller]
    controller --> MainController[MainController.java]
    springmvcxsl_pkg --> model[model]
    model --> UserData[UserData.java]
    main --> webapp[webapp]
    webapp --> WEB-INF[WEB-INF]
    WEB-INF --> server-config[server-config.wsdd]
    WEB-INF --> spring-servlet[spring-servlet.xml]
    WEB-INF --> web[web.xml]
    WEB-INF --> xsl[xsl]
    xsl --> mainView[mainView.xsl]
    root --> target[target]
    target --> classes[classes]
    classes --> com_t[com]
    com_t --> example_t[example]
    example_t --> springmvcxsl_t[springmvcxsl]
    springmvcxsl_t --> TestJaxb[TestJaxb.class]
    springmvcxsl_t --> controller_t[controller]
    controller_t --> MainController_c[MainController.class]
    springmvcxsl_t --> model_t[model]
    model_t --> UserData_c[UserData.class]
    target --> maven-status[maven-status]
    maven-status --> maven-compiler[maven-compiler-plugin]
    maven-compiler --> compile[compile]
    compile --> default-compile[default-compile]
    default-compile --> createdFiles[createdFiles.lst]
    default-compile --> inputFiles[inputFiles.lst]
