treeView-beta
├── .idea/
│   ├── compiler.xml
│   ├── misc.xml
│   ├── modules.xml
│   ├── springmvcxsl.iml
│   ├── vcs.xml
│   └── workspace.xml
├── node_modules/
├── notes/
│   ├── project_files.png
│   └── run.txt
├── src/
│   └── main/
│       ├── java/
│       │   └── com/
│       │       └── example/
│       │           └── springmvcxsl/
│       │               ├── controller/
│       │               │   └── MainController.java :::highlight icon(logos:java) ## controller
│       │               └── model/
│       │                   └── UserData.java :::highlight icon(logos:java) ## data model
│       └── webapp/
│           └── WEB-INF/
│               ├── xsl/
│               │   └── mainView.xsl :::highlight icon(logos:xml) ## view template
│               ├── server-config.wsdd
│               ├── spring-servlet.xml
│               └── web.xml
├── target/
├── .output.txt
├── mermaid-config.json
├── meta.yml
├── package-lock.json
├── package.json :::highlight icon(logos:npm) ## dependencies
├── pom.xml :::highlight icon(logos:maven) ## build config
├── project_files.mmd
├── puppeteer-config.json
└── project_treeview.mmd
