#http://stackoverflow.com/questions/14544991/how-to-configure-slf4j-simple
#1.7.5
org.slf4j.simpleLogger.defaultLogLevel=info
#1.6.6
#org.slf4j.simplelogger.defaultlog=debug

org.slf4j.simpleLogger.showDateTime=true
#other properties documented in http://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html